apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # beekeeper global config
  - beekeeper.configmap.yaml

  ### beekeeper API
  - beekeeper-api.yaml

  ### beekeeper sshd
  - beekeeper-sshd.yaml

